### ISSUE TITLE
IT+ Commands not working

### ISSUE THREAD

**Issue by ghost** [markkimsal/homesecurity#10]
IT+SYSINFO and other IT+ comannds producing this error. 

Output buffer: I

Output buffer: I
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F7"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. 9E"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}
{"type":"error","msg":"Unexpected byte with no error handler set. F6"}

**Comment by markkimsal** [comment]
TT+SYSINFO

**Comment by ghost** [comment]
Working now that I am using the newer build in https://github.com/TANC-security/keypad-firmware
