### ISSUE TITLE
Messages don't reflect Alarm state

### ISSUE THREAD

**Issue by JonRobert** [markkimsal/homesecurity#11]
Hi,
1st, thank you for your work, and for sharing.
1) I have a Vista20P with firmware v8.1
2) I'm running on a 16Mhz Arduino Pro Mini
3) The only software mod was to comment out lines

	if (expect_byt == '\0') {
		Serial.print("{\"type\":\"unknown\",\"byte\":\"");
		print_hex((char)x, 8);
		Serial.println("\"}");
	}

My results are confusing, the messages do not match the alarm state.  Not sure where to look.  Any thoughts?

Thanks
John

Sample of output:

"good morning"
"Starting vista keypad bus"

Status = not armed, one door (switch) open (faulted), AC power:

{"type":"sysinfo","version":"","kpaddr":"16","lrr_supervisor":true}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}

Closed door, now no faults:
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}

Armed Keypad: (home stay)
{"type":"display", "kp17": "active", "kp18": "active", "kp19": "active", "kp20": "active", "kp21": "active", "kp22": "active", "kp23": "active", "beep": "BC", "ARMED_STAY": true, "low_batt": true, "READY": "true", "chime": "off", "ac_power": "on", "ARMED_AWAY": true, "prompt_pos": "-20EC", "msg": "~VYc
57[V_+Y]75555ccE3OCcLf#3L"}
{"type":"display", "kp20": "active", "kp21": "active", "kp22": "active", "kp23": "active", "ARMED_STAY": true, "low_batt": true, "READY": "true", "chime": "on", "bypass_zone": true, "ac_power": "off", "ARMED_AWAY": false, "prompt_pos": "-16F0", "msg": "pBwWpppBw7ppppppBw{~~~~rNv"}
{"type":"error","msg":"Unexpected byte with no error handler set.22"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}
{"type":"error","msg":"Unexpected byte with no error handler set.FE"}
{"type":"status", "armed": "no", "mode": "stay", "ignore_faults": "no", "faulted": "no", "panic": "no"}

**Comment by JonRobert** [comment]
Found alarm signal needs to have no inversions going into the µP.   Once I fixed this the messages made sense.

**Comment by markkimsal** [comment]
Can you explain what you mean by "no inversions going into the uP"? I'd like to make a note of it in the readme or docs somewhere.

**Comment by JonRobert** [comment]
Hi,
First I thank you for your work.  I have it working fine.
Regarding your question;   I had read somewhere the keypad signal was inverted from a normal serial signal.  Thinking I was doing a good thing I added an inversion before going into the µP input.   It didn't work correctly but gave some results that made it seem like it was partially working.

John
