### ISSUE TITLE
Using Max232

### ISSUE THREAD

**Issue by Gilmargolin** [markkimsal/homesecurity#12]
I have hooked the mega board to the vista 20p via a max232 breakout RX is working perfectly. But sending commands to the unit has no affect. Is outwire working for anyone?

**Comment by markkimsal** [comment]
What kind of arduino are you driving the max232 with?

**Comment by markkimsal** [comment]
what's the max232 breakout board? sparkfun?

**Comment by ghost** [comment]
Make sure you on the latest code posted to this link. https://github.com/TANC-security/keypad-firmware
Mark you should remove this posting and just use your latest posting for the code.

Make sure your wiring matches this https://github.com/markkimsal/homesecurity/issues/8.  I tried different opto's  but this was the only one to work for me.

For the serial console when sending your alarm code (12341) to the panel, make sure you have the serial console to Send Carriage Return only. 

I tested this on a Uno, Mega and Nano. All worked for me.  Mine is fully live and operational. I have it setup to a webAPI to get alarm status change requests and to send message data back.

**Comment by Gilmargolin** [comment]
I am using

DZS Elec RS232 DB9 Male Serial Port to TTL Converter MAX3232 Root Module Connector MCU Programme Mobile Root Vehicle Examine and Repair Converter https://www.amazon.com/dp/B072KJSS5C/ref=cm_sw_r_cp_api_g0CIBb7QPS6CP

I simply connected to yellow wire to pin 2 and the green to the pin 3 of the D9 connector of the max232. 

I connected the ttl side RX AND TX to the Mega 2560 board 

I did not connect any other wire to the vista. 

I am using the latest other repository sorry for posting here by mistake

**Comment by ghost** [comment]
Why are you using the MAX3232?  Is that your logic converter for 5v to 12V?   Going with a very simple basic circuit like  https://github.com/markkimsal/homesecurity/issues/8 works perfectly for the 5v/12V logic level connected to a Mega 2560.

**Comment by Gilmargolin** [comment]
The truth is I don’t really know how to read the diagram and what I should buy;( 
I understand I need two resistors 1k ohm
I don’t understand the optico which I should get. Also I don’t understand what the X1 is

**Comment by Gilmargolin** [comment]
I figured out most of the diagram -- only missing what the X1 resistor is, can you send me a link to what it is please.

**Comment by ghost** [comment]
oops missed that one, that should be a 10K resistor.

**Comment by markkimsal** [comment]
It's really simple actually.  That diagram ends up looking something like this:

![img_20180901_155537](https://user-images.githubusercontent.com/54099/44949494-bc77c900-ae00-11e8-81b1-8277edf2682d.jpg)

Get a mini breadboard, some pc871, various resistors, and various jumper wires.  It will look something like that picture.  The LED is not necessary, just so I could see when the data was going out.

The basic idea is that one side of one optocoupler has always on 12v, the other side is signaled from arduino.  When the arduino signals the 12v is allowed through, creating a synchronous signal.

Flip the other optocoupler around and give it constant 3.3 or 5v from arduino, and connect the other side to the panels signal (yellow wire), and when the panel signals it allows the low voltage side through, creating a parallel signal at the lower voltage.

pc817: https://www.amazon.com/dp/B00S4YRMB4/ref=sxts_sxwds-bia_1

wires: https://www.amazon.com/HiLetgo-Breadboard-Prototype-Assortment-Raspberry/dp/B077X7MKHN/ref=sr_1_3

mini breadboard: https://www.amazon.com/ELEGOO-6PCS-tie-points-Breadboard-Arduino/dp/B01EV6SBXQ/ref=sr_1_3

resistor kit:  https://www.amazon.com/Elegoo-Values-Resistor-Assortment-Compliant/dp/B072BL2VX1/ref=sr_1_5

Honestly, I never got a max232 working with the alarm panels.  I think it has something to do with the negative voltage of the RS-232 spec that the panel doesn't like.  The optocouplers are only like $5 for 10, so if you have wires and resistors and a breadboard, you're golden.

Outside of github I can mail you a maker kit as pictured on http://alarmtool.com if you paypal me some bucks (shopping cart not working yet).  It has a working arduino with firmware, opto thingies, resistors, and screw terminals for the panel wires.

**Comment by Gilmargolin** [comment]
You are the best! I found that I have it all apart from the optocoupler which should arrive tomorrow. Will keep you posted. Many thanks for your support of the community!!

**Comment by Gilmargolin** [comment]
Ok so I finally got it connected and I am getting both signal from the vista and able to set it to armed. 

I am getting an error on the other keypad with a beep sound and it says Open Ckt

Any idea what this is?

**Comment by Gilmargolin** [comment]
Ok so I finally got it connected and I am getting both signal from the vista and able to set it to armed. 

I am getting an error on the other keypad with a beep sound and it says Open Ckt

Any idea what this is?

**Comment by Gilmargolin** [comment]
I figured it out - i put a wrong valued resistor of 200ohm. Works perfect now!!!! Thanks
