### ISSUE TITLE
Using a 12v regulator as a level converter?

### ISSUE THREAD

**Issue by skandragon** [markkimsal/homesecurity#3]
I've never seen a 5 VDC regulator used as a signal level converter before.  While it might work, I would be afraid it would be risky to use in production.

I think a better solution would be to use a simple optocoupler (probably in both directions) to properly drive the signal.  This may also allow you to invert the signal automatically in hardware, and then not have to worry about the inverted logic in your code.  It also ensures that if something goes Really Wrong, the arduino is less likely to be fried, or the alarm is less likely to be damaged.

**Comment by markkimsal** [comment]
I have 2, one is using an optocoupler and the original is still using the regulator.  I just didn't update the documentation.

**Comment by markkimsal** [comment]
I'd be  happy to take pull requests for updates to the readme or any new hardware documentation.
