### ISSUE TITLE
Minor duplications in alta_veesta on_status function

### ISSUE THREAD

**Issue by ghost** [markkimsal/homesecurity#7]
In the on_status function
short exit_delay = (cbuf[22] & 0x02);
Outputted twice for the same value.
	Serial.print(", \"**_exit_delay_**\": ");
	if (**_exit_delay_**) {
		Serial.print("\"yes\"");
	} else {
		Serial.print("\"no\"");
	}
and
	Serial.print(", \"**_ignore_faults_**\": ");
	if (**_exit_delay_**) {
		Serial.print("\"yes\"");
	} else {
		Serial.print("\"no\"");
	}

**Comment by markkimsal** [comment]
Does it only come on during exit delay?  I think I've seen it on during other times.

**Comment by markkimsal** [comment]
During normal, disarmed operation this bit turns on when anything is faulted:

{"type":"status","armed": "no", "exit_delay": "yes", "mode": "away", "ignore_faults": "yes", "faulted": "yes", "panic": "no"}

During exit delay after setting away or stay:


{"type":"status","armed": "yes", "exit_delay": "yes", "mode": "away", "ignore_faults": "yes", "faulted": "no", "panic": "no"}

{"type":"display", "kp17": "active", "kp18": "active", "kp19": "active", "kp20": "active", "kp21": "active", "kp22": "active", "kp23": "active", "ARMED_STAY": "false", "READY": "false", "chime": "off", "ac_power": "on", "ARMED_AWAY": "true","msg": "ARMED ***AWAY***May Exit Now  20"}

When I bypass a zone it produces no status (F2) messages.  So it's not an active_fault / bypass_fault sort of bit.

It doesn't seem to indicate entry/exit zones from perimeter zones either.  

It could be that this bit is indicating the LED light "ready", but it's not on an F7 message, which is usually where keypad instructions are located.

I can't find a situation where it doesn't exactly mirror the value of "faulted".

**Comment by markkimsal** [comment]
Since that flag doesn't indicate an entry/exit delay I've renamed it to ignore_faults and removed the extra json.
